app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('game/', include('game.urls', namespace='game')),
    path('', include('users.urls', namespace='users')),
    path('tournaments/', include('tournaments.urls', namespace='tournaments')),
]
# 1 url-адрес / фукция / обращение

game/urls.py
from django.urls import path

from game import views

app_name = 'game'

urlpatterns = [
    path('', views.create_game, name='create_game'),
    # path('board/', views.board, name='board'),
    # создаёт новую сессию и редиректит
    path("new/", views.new_game, name="new_game"),
    # собственно доска игры
    path("<str:game_id>/", views.board, name="board"),
]
# 1 url-адрес / фукция / обращение

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]
# 1 url-адрес / фукция / обращение

tournaments/urls.py
from django.urls import path

from tournaments import views

app_name = 'tournaments'

urlpatterns = [
    path('', views.tournaments, name='tournaments'),
]
# 1 url-адрес / фукция / обращение

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('leaders/', views.leaders, name='leaders'),
]
# 1 url-адрес / фукция / обращение

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django import forms

def home(request):
    content = {
        'tournaments': [
            ['Блиц', 'осталось 00:25', '1ч', '5'],
            ['Ежедневный турнир', 'осталось 03:30', '8ч', '32'],
            ['SitAndGo', 'завершено', '3ч', '14'],
            ['Блиц', 'завершено', '1ч', '8'],
            ['SitAndGo', 'завершено', '4ч', '12'],
            ['SitAndGo', 'завершено', '2ч', '16'],
            ['Блиц', 'завершено', '2ч', '10'],
        ],
        'waiting': [
            ['Давид',    '2406', 'Короткие'],
            ['Артур',    '2100', 'Длинные'],
            ['Арам',     '1950', 'Короткие'],
            ['Грант',    '2105', 'Длинные'],
            ['Арсен',    '1780', 'Короткие'],
            ['Нарек',    '2250', 'Длинные'],
            ['Ваге',     '1600', 'Короткие'],
            ['Геворг',   '2400', 'Длинные'],
            ['Серж',     '1823', 'Короткие'],
            ['Тигран',   '2022', 'Длинные'],
            ['Левон',    '2155', 'Короткие'],
            ['Ашот',     '1888', 'Длинные'],
            ['Самвел',   '1701', 'Короткие'],
            ['Армен',    '2303', 'Длинные'],
            ['Сурен',    '1999', 'Короткие'],
        ],
    }
    return render(request, 'main/home.html', content)

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'image/favicon.ico' %}">

    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {% block CSS %}{% endblock CSS %}

    <title>Нарды</title>
</head>

<body>
    <nav>
        <ul>
            <img src="{% static 'image/nard-logo.png' %}" style="height: auto; width: 100%;">
            <li class="{% if request.path == '/' %}active{% endif %}"> <a href="{% url "main:home" %}">Главная</a> </li>
            <li class="{% if request.path == '/game/' %}active{% endif %}"> <a href="{% url "game:create_game" %}">Играть</a>
                {% comment %} <ul class="submenu">
                    <li><a href="#">Длинные</a></li>
                    <li><a href="#">Короткие</a></li>
                </ul> {% endcomment %}
            </li>
            <li class="{% if request.path == '/tournaments/' %}active{% endif %}"> <a href="{% url "tournaments:tournaments" %}">Турниры</a>
                {% comment %} <ul class="submenu">
                    <li><a href="#">Текущие</a></li>
                    <li><a href="#">Будущие</a></li>
                </ul> {% endcomment %}
            </li>
            <li class="{% if request.path == '/leaders/' %}active{% endif %}"> <a href="{% url "users:leaders" %}">Лидеры</a> </li>
            <li class="{% if request.path == '/profile/' %}active{% endif %}"> <a href="{% url "users:profile" %}">Профиль</a> </li>
        </ul>
    </nav>
    <div class="content">
        {% block CONTENT %}{% endblock CONTENT %}
    </div>
    {% block JS %}{% endblock JS %}
</body>
</html>

main/templates/main/home.html
{% extends "main/base.html" %}
{% load static %}

{% block CSS %}
    <link rel="stylesheet" href="{% static "css/home.css" %}">
{% endblock CSS %}

{% block JS %}
    <script type="module" src="{% static 'js/home.js' %}"></script>
{% endblock JS %}

{% block CONTENT %}
<div style="background-image: url({% static 'image/human.png' %})"></div>
<div class="containerA">
    <div class="areaA5">
        <button id="btnCreateGame">Создать игру</button>
    </div>
    <div class="areaA1">
        <button id="btnProfile">Профиль</button>
    </div>
    <div class="areaA2">
        <p class="tableHeader">Последние турниры</p>
        <table>
            <tbody>
                {% for data in tournaments %}
                    <tr onclick="document.location = {{ data.9 }}">
                        <td><div style="background-image: url({{ data.8 }})"></div></td>
                        <td style="text-align: left; padding-left: 10px; width: 190px;">{{ data.0 }}</td>
                        <td>{{ data.1 }}</td>
                        <td style="text-align: left;">{{ data.2 }}</td>
                        <td><img src="{% static 'image/human.png' %}" style="height: auto; width: 10px;"></td>
                        <td style="text-align: left;">{{ data.3 }}</td>
                    </tr>
                {% endfor %}
                {% comment %} <tr onclick="document.location = '/user/Серый Волк';"> {% endcomment %}
                {% comment %} <div class="row-avatar" style="background-image: url('/img/noavatar.png')"></div> {% endcomment %}
            </tbody>
        </table>
    </div>
    <div class="areaA3">
        <div class="areaA3-1">
            <p class="tableHeader">Короткие нарды</p>
            <table class="leaders">
                <tbody>
                    <tr>
                        <td><img src="{% static 'image/medal1.png' %}" style="height: 40px; width: auto;"></td>
                        <td>Давид</td>
                        <td>2406</td>
                    </tr>
                    <tr>
                        <td><img src="{% static 'image/medal2.png' %}" style="height: 40px; width: auto;"></td>
                        <td>Артур</td>
                        <td>2155</td>
                    </tr>
                    <tr>
                        <td><img src="{% static 'image/medal3.png' %}" style="height: 40px; width: auto;"></td>
                        <td>Арсен</td>
                        <td>2075</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="areaA3-2">
            <p class="tableHeader">Длинные нарды</p>
            <table class="leaders">
                <tbody>
                    <tr>
                        <td><img src="{% static 'image/medal1.png' %}" style="height: 40px; width: auto;"></td>
                        <td>Сурен</td>
                        <td>2400</td>
                    </tr>
                    <tr>
                        <td><img src="{% static 'image/medal2.png' %}" style="height: 40px; width: auto;"></td>
                        <td>Тигран</td>
                        <td>2303</td>
                    </tr>
                    <tr>
                        <td><img src="{% static 'image/medal3.png' %}" style="height: 40px; width: auto;"></td>
                        <td>Армен</td>
                        <td>2250</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="areaA4">
        <p class="tableHeader">Зал ожидания</p>
        <table>
            <tbody>
                {% for data in waiting %}
                    <tr>
                        <td>{{ data.0 }}</td>
                        <td>{{ data.1 }}</td>
                        <td>{{ data.2 }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
  </div>
{% endblock CONTENT %}